export const SITE = {
  title: "AllTheCookies",
  author: "Luks17",
  url: "https://www.allthecookies.com.br",
  description:
    "Um simples site pessoal sobre tecnologia para pessoas que gostam de tecnologia",
  socialImage: "@/assets/Logo.png",

  postsPerPage: 6,
  maxTagsPerPost: 4,
  origin: "",
  basePathname: "/",
  trailingSlash: false,
  tags: [
    "linux",
    "windows",
    "outros",
    "hardware",
    "microsoft",
    "apple",
    "google",
    "html/css",
    "astrojs",
    "tailwind",
    "react",
    "laravel",
    "javascript",
    "rust",
    "go",
    "python",
    "c/c++",
    "php",
    "web",
    "terminal",
    "vim",
    "redes",
    "gaming",
    "framework",
    "distro",
    "review",
    "performance",
    "otimização",
    "server",
    "cloud",
    "IA",
    "docker",
    "containers",
    "git",
    "dados",
    "sql",
    "nosql",
    "futurologia",
  ],
};
