export const SITE = {
  title: "AllTheCookies",
  author: "Luks17",
  description: "Personal Website about technology",
  socialImage: "",

  postsPerPage: 3,
  maxTagsPerPost: 4,
  origin: "",
  basePathname: "/",
  trailingSlash: false,
  tags: [
    "linux",
    "windows",
    "outros",
    "hardware",
    "microsoft",
    "apple",
    "html/css",
    "astrojs",
    "tailwind",
    "react",
    "laravel",
    "javascript",
    "rust",
    "go",
    "python",
    "c/c++",
    "php",
    "web",
    "terminal",
    "vim",
    "redes",
    "gaming",
    "framework",
    "distro",
    "review",
    "performance",
    "server",
    "cloud",
    "IA",
    "docker",
    "git",
    "dados",
    "sql",
    "nosql",
  ],
};
